### ISSUE TITLE
Unable to find the specified form.

### ISSUE THREAD

**Issue by nicmalate** [k-sys/covid-19#61]
I'm using Python 3.8.2 on Windows. I fixed this problem when i run data in MCMC Model. 

Traceback (most recent call last):
  File "c:/Users/nicma/Desktop/PythonScripts/Tesi/main.py", line 362, in <module>
    models[state] = create_and_run_model(state, grp.droplevel(0))
  File "c:/Users/nicma/Desktop/PythonScripts/Tesi/main.py", line 348, in create_and_run_model
    return MCMCModel(name, onset, cumulative_p_delay).run()
  File "c:/Users/nicma/Desktop/PythonScripts/Tesi/main.py", line 262, in run
    step_size = pm.HalfNormal('step_size', sigma=.03)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymc3\distributions\distribution.py", line 46, in __new__
    dist = cls.dist(*args, **kwargs)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymc3\distributions\distribution.py", line 57, in dist
    dist.__init__(*args, **kwargs)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymc3\distributions\continuous.py", line 835, in __init__
    self.mean = tt.sqrt(2 / (np.pi * self.tau))
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\tensor\var.py", line 233, in __rmul__
    return theano.tensor.basic.mul(other, self)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\op.py", line 669, in __call__
    thunk = node.op.make_thunk(node, storage_map, compute_map,
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cmodule.py", line 2405, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\nicma\AppData\Local\Programs\Python\Python38-32\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing mb63002e4cb3b72a8678617030d8b841c60d1b77d8eb3a2052c9a8bc46863bcd5: Impossibile trovare il modulo specificato.

Can you help me?

**Comment by nicmalate** [comment]
I close the issue because I solved the problem. The problem was mingw. Uninstall that
